/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.tinyrcp.example.dummy;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JComponent;
import javax.swing.JMenuItem;
import javax.swing.JTabbedPane;
import org.tinyrcp.App;
import org.tinyrcp.TinyFactory;
import org.tinyrcp.TinyPlugin;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

/**
 *
 * @author sbodmer
 */
public class JDummyPlugin extends javax.swing.JPanel implements TinyPlugin, ActionListener {

    TinyFactory factory = null;
    App app = null;

    /**
     * Creates new form JTabsPlugin
     */
    public JDummyPlugin(TinyFactory factory) {
        this.factory = factory;

        initComponents();

    }

    //**************************************************************************
    //*** API
    //**************************************************************************
    
    //**************************************************************************
    //*** TinyPlugin
    //**************************************************************************
    @Override
    public TinyFactory getPluginFactory() {
        return factory;
    }

    @Override
    public String getPluginName() {
        return factory.getFactoryName();
    }

    @Override
    public void setPluginName(String name) {
        //---
    }

    @Override
    public JComponent getVisualComponent() {
        //--- Return myself as the visual component
        return this;
    }

    @Override
    public JComponent getConfigComponent() {
        //--- No configuration component
        return null;
    }

    @Override
    public Object doAction(String message, Object argument, Object subject) {
        return null;
    }

    @Override
    public void setup(App app, Object argument) {
        this.app = app;

    }

    @Override
    public void configure(Element config) {
        if (config == null) return;

        //--- Configure the component by reading the passed element
    }

    @Override
    public void cleanup() {
        //--- Clean the resources used here
    }

    @Override
    public void saveConfig(Element config) {
        if (config == null) return;
        
        //--- Store the configuration in the passed element
    }

    @Override
    public Object getProperty(String name) {
        return null;
    }

    @Override
    public void setProperty(String name, Object value) {
        //---
    }

    
    //**************************************************************************
    //*** ActionListener
    //**************************************************************************
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getActionCommand().equals("someaction")) {
            //--- Do somwthing Goreman !!!
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TA_Dummy = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        TA_Dummy.setEditable(false);
        TA_Dummy.setColumns(20);
        TA_Dummy.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        TA_Dummy.setRows(5);
        TA_Dummy.setText("Welcome to the example panel plugin\n\nA plugin in TinyRCP concept is composed of\n- A factory\n- A component for visual  display");
        jScrollPane1.setViewportView(TA_Dummy);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextArea TA_Dummy;
    protected javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
