/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.tinyrcp.components;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import javax.swing.JComponent;

/**
 * Component which implements the mouse listener so it could be moved within the
 * parent panel (useful for LayeredPane integration)
 *
 * @author sbodmer
 */
public class JMoveablePanel extends javax.swing.JPanel implements MouseListener, MouseMotionListener, ActionListener {

    Point reference = null;

    /**
     * Creates new form JMoveablePanel
     */
    public JMoveablePanel() {
        initComponents();

        PN_Top.addMouseListener(this);
        PN_Top.addMouseMotionListener(this);
        BT_Close.addActionListener(this);

    }

    //**************************************************************************
    //*** API
    //**************************************************************************
    public void setTitle(String title) {
        LB_Title.setText(title);
    }

    /**
     * Set the center component
     * 
     * @param jcomp 
     */
    public void setCustomComponent(JComponent jcomp) {
        BorderLayout layout = (BorderLayout) getLayout();
        remove(layout.getLayoutComponent(BorderLayout.CENTER));
        add(jcomp, BorderLayout.CENTER);
        Dimension pref = jcomp.getPreferredSize();
        setSize(pref.width,pref.height+PN_Top.getHeight());
        revalidate();
    }

    //**************************************************************************
    //*** MouseListener
    //**************************************************************************
    @Override
    public void mouseClicked(MouseEvent e) {
        //---
    }

    @Override
    public void mousePressed(MouseEvent e) {
        if (e.getSource() == PN_Top) {
            reference = e.getPoint();
        }
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        //---
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        //---
    }

    @Override
    public void mouseExited(MouseEvent e) {
        //---
    }

    //**************************************************************************
    //*** MouseMotionListener
    //**************************************************************************
    @Override
    public void mouseDragged(MouseEvent e) {
        if (e.getSource() == PN_Top) {
            Point pt = e.getPoint();
            Point diff = new Point(pt.x - reference.x, pt.y - reference.y);
            Point loc = getLocation();
            setLocation(loc.x + diff.x, loc.y + diff.y);
            repaint();
        }
    }

    @Override
    public void mouseMoved(MouseEvent e) {
        //---
    }

    //**************************************************************************
    //*** ActionListener
    //**************************************************************************
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getActionCommand().equals("close")) {
            setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PN_Top = new javax.swing.JPanel();
        LB_Title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BT_Close = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        PN_Top.setLayout(new java.awt.BorderLayout());

        LB_Title.setBackground(java.awt.Color.lightGray);
        LB_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PN_Top.add(LB_Title, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(java.awt.Color.gray);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        BT_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/tinyrcp/Resources/Icons/16x16/window-close.png"))); // NOI18N
        BT_Close.setActionCommand("close");
        BT_Close.setBorderPainted(false);
        BT_Close.setContentAreaFilled(false);
        BT_Close.setPreferredSize(new java.awt.Dimension(26, 26));
        jPanel2.add(BT_Close);

        PN_Top.add(jPanel2, java.awt.BorderLayout.EAST);

        add(PN_Top, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton BT_Close;
    protected javax.swing.JLabel LB_Title;
    protected javax.swing.JPanel PN_Top;
    protected javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
