/*
 * Copyright (C) 2018 sbodmer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.tinyrcp.grid;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import org.tinyrcp.TinyPlugin;

/**
 *
 * @author sbodmer
 */
public class JGridCell extends javax.swing.JPanel implements ActionListener {

    TinyPlugin plugin = null;
    ActionListener listener = null;

    /**
     * Creates new form JGridCell
     */
    public JGridCell(TinyPlugin plugin, String title, ActionListener listener) {
        this.plugin = plugin;
        this.listener = listener;

        initComponents();
        add(plugin.getVisualComponent(), BorderLayout.CENTER);
        LB_Title.setText(title);

        BT_Close.addActionListener(this);
        BT_Rename.addActionListener(this);

    }

    //**************************************************************************
    //*** API
    //**************************************************************************
    public TinyPlugin getPlugin() {
        return plugin;
    }

    public String getTitle() {
        return LB_Title.getText().trim();
    }
    
    //**************************************************************************
    //*** ActionListener
    //**************************************************************************
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getActionCommand().equals("close")) {
            //--- Forward
            e.setSource(this);
            if (listener != null) listener.actionPerformed(e);

        } else if (e.getActionCommand().equals("rename")) {
            String name = JOptionPane.showInputDialog(this, "", LB_Title.getText());
            if (name != null) {
                LB_Title.setText(name);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PN_Top = new javax.swing.JPanel();
        LB_Title = new javax.swing.JLabel();
        BT_Close = new javax.swing.JButton();
        BT_Rename = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        PN_Top.setBackground(java.awt.Color.gray);
        PN_Top.setLayout(new java.awt.BorderLayout());

        LB_Title.setText("...");
        PN_Top.add(LB_Title, java.awt.BorderLayout.CENTER);

        BT_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/tinyrcp/Resources/Icons/16x16/window-close.png"))); // NOI18N
        BT_Close.setActionCommand("close");
        BT_Close.setBorderPainted(false);
        BT_Close.setContentAreaFilled(false);
        BT_Close.setPreferredSize(new java.awt.Dimension(28, 28));
        PN_Top.add(BT_Close, java.awt.BorderLayout.EAST);

        BT_Rename.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/tinyrcp/Resources/Icons/16x16/edit.png"))); // NOI18N
        BT_Rename.setToolTipText("Rename");
        BT_Rename.setActionCommand("rename");
        BT_Rename.setBorderPainted(false);
        BT_Rename.setContentAreaFilled(false);
        BT_Rename.setPreferredSize(new java.awt.Dimension(26, 26));
        PN_Top.add(BT_Rename, java.awt.BorderLayout.WEST);

        add(PN_Top, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton BT_Close;
    protected javax.swing.JButton BT_Rename;
    protected javax.swing.JLabel LB_Title;
    protected javax.swing.JPanel PN_Top;
    // End of variables declaration//GEN-END:variables

}
