/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.tinyrcp;

import javax.swing.SwingUtilities;

/**
 * Example of a main entry point<p>
 *
 * @author sbodmer
 */
public class JAppLauncher extends javax.swing.JFrame implements AppLauncher.AppBootListener {

    protected String[] args = null;

    /**
     * Creates new form JAppLauncher
     */
    public JAppLauncher(String args[]) {
        this.args = args;
        initComponents();
        

    }

    //**************************************************************************
    //*** API
    //**************************************************************************
    
    //**************************************************************************
    //*** AppBootListener
    //**************************************************************************
    @Override
    public void appBootStarted() {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
                PB_Progress.setIndeterminate(true);
            }
        });

    }

    @Override
    public void appBootProgress(final String message, final int current, final int total) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                PB_Progress.setIndeterminate(total==0);
                PB_Progress.setMaximum(total);;
                PB_Progress.setValue(current);
                PB_Progress.setString(message);
            }
        });
    }

    @Override
    public void appBootFinished(final Object mc) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                setVisible(false);
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PB_Progress = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        jPanel1.setLayout(new java.awt.BorderLayout());

        PB_Progress.setPreferredSize(new java.awt.Dimension(150, 26));
        PB_Progress.setString("");
        PB_Progress.setStringPainted(true);
        jPanel1.add(PB_Progress, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jLabel1.setText("Launching application");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(400, 53));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Pass a list of jar to load dynamically<p>
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAppLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAppLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAppLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAppLauncher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //--- Prepare the loader
                String libs[] = {
                    "lib/ext"
                };

                //--- Parse arguments
                String appName = "GenericApp";
                try {
                    for (int i = 0; i < args.length; i++) {
                        if (args[i].equals("-name")) {
                            appName = args[i + 1];
                            i++;

                        }
                    }

                } catch (ArrayIndexOutOfBoundsException ex) {
                    System.err.println("(E) Arguments error");

                }

                //--- Prepare splash screen
                JAppLauncher japp = new JAppLauncher(args);
                
                //--- Start boot process
                //--- When the boot has finished, teh splash screen should close itself
                AppLauncher.boot(japp, libs, args, appName);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JProgressBar PB_Progress;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JPanel jPanel1;
    protected javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
