/*
 * Copyright (C) 2017 sbodmer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.tinyrcp;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author sbodmer
 */
public class JPluginsFrame extends javax.swing.JFrame implements ListSelectionListener {

    App app = null;
    
    DefaultListModel<TinyFactory> model = new DefaultListModel<>();
    
    /**
     * Creates new form JPlugins
     */
    public JPluginsFrame() {
        initComponents();
        
        LI_Factories.setModel(model);
        
    }
    //**************************************************************************
    //*** API
    //**************************************************************************
    public void initialize(App app) {
        this.app = app;
    
        LI_Factories.setCellRenderer(new JTinyFactoryCellRenderer(app, false));
        ArrayList<TinyFactory> facs = app.getFactories(null);
        for (int i=0;i<facs.size();i++) model.addElement(facs.get(i));
        
        LI_Factories.addListSelectionListener(this);
        if (facs.size() > 0) LI_Factories.setSelectedIndex(0);
    }
    
    //**************************************************************************
    //*** ListSelectionListener
    //**************************************************************************
    @Override
    public void valueChanged(ListSelectionEvent e) {
        if (e.getSource() == LI_Factories) {
            if (e.getValueIsAdjusting() == false) {
                TinyFactory f = LI_Factories.getSelectedValue();
                if (f != null) {
                    LB_Name.setText(f.getFactoryName());
                    LB_Name.setIcon(f.getFactoryIcon(22));
                    TP_Description.setText(f.getFactoryDescription());
                    
                    String tmp = (String) f.getProperty(TinyFactory.PROPERTY_VERSION);
                    LB_Version.setText(tmp==null?"N/A":tmp);
                    
                    tmp = (String) f.getProperty(TinyFactory.PROPERTY_AUTHOR);
                    LB_Author.setText(tmp==null?"N/A":tmp);
                    
                    tmp = (String) f.getProperty(TinyFactory.PROPERTY_COPYRIGHT_TEXT);
                    LB_Copyright.setText(tmp==null?"N/A":tmp);
                    
                    tmp = (String) f.getProperty(TinyFactory.PROPERTY_LICENCE_TEXT);
                    TP_Licence.setText(tmp==null?"N/A":tmp);
                    
                    tmp = app.getFactoryOrigin(f);
                    LB_Origin.setText(tmp==null?"N/A":tmp);
                    
                    
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LB_Name = new javax.swing.JLabel();
        LB_Author = new javax.swing.JLabel();
        LB_Origin = new javax.swing.JLabel();
        LB_Version = new javax.swing.JLabel();
        LB_Copyright = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TP_Description = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        TP_Licence = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LI_Factories = new javax.swing.JList<>();

        LB_Name.setText("Name");

        LB_Author.setText("Author");

        LB_Origin.setText("Origin");

        LB_Version.setText("Version");

        LB_Copyright.setText("Copyright");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LB_Origin)
                    .addComponent(LB_Version)
                    .addComponent(LB_Name)
                    .addComponent(LB_Author)
                    .addComponent(LB_Copyright))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(LB_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LB_Version)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LB_Author)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LB_Copyright)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LB_Origin)
                .addContainerGap())
        );

        TP_Description.setContentType("text/html"); // NOI18N
        jScrollPane2.setViewportView(TP_Description);

        TP_Licence.setContentType("text/html"); // NOI18N
        jScrollPane3.setViewportView(TP_Licence);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(400, 480));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 134));

        jScrollPane1.setViewportView(LI_Factories);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.WEST);

        setBounds(0, 0, 810, 630);
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel LB_Author;
    protected javax.swing.JLabel LB_Copyright;
    protected javax.swing.JLabel LB_Name;
    protected javax.swing.JLabel LB_Origin;
    protected javax.swing.JLabel LB_Version;
    protected javax.swing.JList<TinyFactory> LI_Factories;
    protected javax.swing.JTextPane TP_Description;
    protected javax.swing.JTextPane TP_Licence;
    protected javax.swing.JPanel jPanel1;
    protected javax.swing.JPanel jPanel2;
    protected javax.swing.JPanel jPanel3;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JScrollPane jScrollPane2;
    protected javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    
}
