package org.tinyrcp.desk;

import javax.swing.Icon;
import javax.swing.JComponent;
import org.tinyrcp.App;
import org.tinyrcp.TinyFactory;
import org.tinyrcp.TinyPlugin;
import org.w3c.dom.Element;

/**
 *
 * @author sbodmer
 */
public class JDeskFactory extends javax.swing.JPanel implements TinyFactory {

    /**
     *
     */
    public JDeskFactory() {
        initComponents();
    }

    //**************************************************************************
    //*** PluginFactory
    //**************************************************************************
    @Override
    public Icon getFactoryIcon(int size) {
        return LB_Name.getIcon();
    }

    @Override
    public String getFactoryName() {
        return LB_Name.getText();
    }

    @Override
    public String getFactoryDescription() {
        return LB_Description.getText();
    }

    @Override
    public String getFactoryCategory() {
        return PLUGIN_CATEGORY_PANEL;
    }

    @Override
    public JComponent getFactoryConfigComponent() {
        return null;
    }
    
    @Override
    public void configure(Element config) {
        //---
    }

    @Override
    public void store(Element config) {
        //---
    }

    @Override
    public void destroy() {
        //---
    }

    @Override
    public void initialize(App app) {
        //---
    }

    public JComponent getConfigComponent() {
        return null;
    }

    public TinyPlugin newPlugin(Object arg) {
        return new JDeskPlugin(this);
    }

    @Override
    public String getFactoryFamily() {
        return PLUGIN_FAMILY_CONTAINER;
    }

    @Override
    public Object getProperty(String property) {
        return null;
    }

    @Override
    public boolean doesFactorySupport(Object obj) {
        return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_Name = new javax.swing.JLabel();
        LB_Description = new javax.swing.JLabel();

        LB_Name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/tinyrcp/desk/Resources/Icons/22x22/desk.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/tinyrcp/desk/Desk"); // NOI18N
        LB_Name.setText(bundle.getString("factory_name")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel LB_Description;
    protected javax.swing.JLabel LB_Name;
    // End of variables declaration//GEN-END:variables

}
